### ISSUE TITLE
Error when running generate-pygments-css

### ISSUE THREAD

**Issue by DallasBelt** [gregorias/anki-code-highlighter#70] opened 2023-11-14 13:26 UTC
Hello dear developer. I followed your guide to add a different style for Pygments, but when I ran `generate-pygments-css` it throwed an error at the beggining:
```
ERROR	No content to parse.
ERROR	PropertyValue: Unknown syntax or no value:  
ERROR	CSSStyleDeclaration: Syntax Error in Property: color:
```
I assumed that the next lines that followed the error were the generated style, so I copy them to a file, which I placed in the addon directory `~/.local/share/Anki2/addons21/112228974/assets`. Then, I changed the settings in Anki to point to that style, but it's still using the default Solarized. Maybe I messed up at some point. Could you please help me?

Thanks in advance.

**Comment by gregorias** [comment] 2023-11-15 07:33
Hi @DallasBelt, thank you for reaching out. I'll take a look when I have some time. In the meantime, could you provide reproduction steps and generally more details?

**Comment by DallasBelt** [comment] 2023-11-19 02:26
Sorry for the late reply. I was playing around with the css file and after closing and opening Anki, it's now working. Don't know about the errors, though. Let me know if I can help!

**Comment by gregorias** [comment] 2023-11-19 07:51
I'm glad that everything worked out in the end.

Since we can no longer reproduce this, I don't think it's worth the time to sleuth around, so I'm closing this ticket.

**Closed by gregorias** 2023-11-19 07:51 UTC
Labels: question
